//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookaroom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrades
    {
        public int ticket_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> event_id { get; set; }
        public Nullable<int> seat_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Butaca Butaca { get; set; }
        public virtual Esdeveniments Esdeveniments { get; set; }
        public virtual Usuaris Usuaris { get; set; }
    }
}
