//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookaroom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventari
    {
        public Inventari()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int inventory_id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
