//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookaroom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int id { get; set; }
        public int sent_id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public string status { get; set; }
    
        public virtual Usuaris Usuaris { get; set; }
    }
}
