//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookaroom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookaroomEntities : DbContext
    {
        public bookaroomEntities()
            : base("name=bookaroomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Butaca> Butaca { get; set; }
        public DbSet<Entrades> Entrades { get; set; }
        public DbSet<Esdeveniments> Esdeveniments { get; set; }
        public DbSet<Inventari> Inventari { get; set; }
        public DbSet<Mensajes> Mensajes { get; set; }
        public DbSet<Sales> Sales { get; set; }
        public DbSet<Usuaris> Usuaris { get; set; }
    }
}
