//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookaroom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public Sales()
        {
            this.Butaca = new HashSet<Butaca>();
            this.Esdeveniments = new HashSet<Esdeveniments>();
        }
    
        public int room_id { get; set; }
        public Nullable<int> inventory_id { get; set; }
        public int dimensions { get; set; }
        public int max_capacity { get; set; }
        public int num_seats { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<Butaca> Butaca { get; set; }
        public virtual ICollection<Esdeveniments> Esdeveniments { get; set; }
        public virtual Inventari Inventari { get; set; }
    }
}
